### ISSUE TITLE
Failed to generate CyHy report for DHS_FEMA

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cyhy-reports#92]
# 🐛 Summary #

The CyHy reporting process failed to generate a report for the `DHS_FEMA` org this morning.

## To reproduce ##

Run `sudo -u cyhy cyhy-report --cyhy-section cyhy --scan-section scan --final --encrypt DHS_FEMA` and watch it fail.

## Expected behavior ##

The report for `DHS_FEMA` should be produced successfully.

## Any helpful log output or screenshots ##

Paste the results here:

```console
$ sudo -u cyhy cyhy-report --cyhy-section cyhy --scan-section scan --final --encrypt DHS_FEMA
/usr/lib/python2.7/dist-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
Generating report for DHS_FEMA ...
Traceback (most recent call last):
  File "/usr/local/bin/cyhy-report", line 11, in <module>
    generate_report.main()
  File "/usr/local/lib/python2.7/dist-packages/cyhy_report/customer/generate_report.py", line 3566, in main
    was_encrypted, results = generator.generate_report()
  File "/usr/local/lib/python2.7/dist-packages/cyhy_report/customer/generate_report.py", line 344, in generate_report
    self.__generate_attachments()
  File "/usr/local/lib/python2.7/dist-packages/cyhy_report/customer/generate_report.py", line 2403, in __generate_attachments
    self.__generate_sub_org_summary_attachment()
  File "/usr/local/lib/python2.7/dist-packages/cyhy_report/customer/generate_report.py", line 2996, in __generate_sub_org_summary_attachment
    for row in self.__results["ss0_descendant_data"]:
KeyError: 'ss0_descendant_data'
```

**Comment by jsf9k** [comment]
The problem appears to be that the `DHS_FEMA_Diaster` suborg was added recently, but it has a start data in the future.  We reach this line https://github.com/cisagov/cyhy-reports/blob/63b896a2e4cfe946b446cbfe034888a2e8a4fe8a/cyhy_report/customer/generate_report.py#L3002 because this condition https://github.com/cisagov/cyhy-reports/blob/63b896a2e4cfe946b446cbfe034888a2e8a4fe8a/cyhy_report/customer/generate_report.py#L2950 is satisfied, but the process then crashes because `"ss0_descendant_data"` is not a key in the `self.__results` dictionary.
